//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCHS_March_.Models.Data_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assistant
    {
        public int Id { get; set; }
        public string Username { get; set; }
    
        public virtual Compliant Compliant { get; set; }
    }
}
