//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCHS_March_.Models.Data_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCH_EntitiesContainer : DbContext
    {
        public CCH_EntitiesContainer()
            : base("name=CCH_EntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compliant> Compliants { get; set; }
        public virtual DbSet<Representation> Representations { get; set; }
        public virtual DbSet<Complainant> Complainants { get; set; }
        public virtual DbSet<Advisor> Advisors { get; set; }
        public virtual DbSet<BodyCorporate> BodyCorporates { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }
}
