//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCHS_March_.Models.Data_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complainant
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public string PO_Box { get; set; }
        public string Tel_Number { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Compliant Compliant { get; set; }
        public virtual Representation Representation { get; set; }
    }
}
