//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCHS_March_.Models.Data_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compliant
    {
        public int Id { get; set; }
        public string SubjectMatter { get; set; }
        public string Details { get; set; }
        public string MatterEscalation { get; set; }
        public string Purpose { get; set; }
        public string PurposedOutcome { get; set; }
        public string YearExplanation { get; set; }
        public string ConsentToInvestigation { get; set; }
        public System.DateTime DateOfSubmission { get; set; }
    
        public virtual BodyCorporate BodyCorporate { get; set; }
        public virtual Complainant Complainant { get; set; }
    }
}
